#sudo: required
language: node_js
node_js:
  - lts/*
script:
  - bash ./deploy.sh
branches:
  only:
    - master
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=c29c29876c8c0b7950babc63b0f09bb92edd7b30c4f4bec2d427a8f5d9116e9a
  email: false
