#sudo: required
language: node_js
node_js:
  - lts/*
script:
  - bash ./deploy.sh
#deploy:
#  provider: pages
#  skip-cleanup: true
#  local_dir: docs/.vuepress/dist
#  github-token: b0b97cd6fbb723dcaa848e02253ad4f2ced617f5 # a token generated on github allowing travis to push code on you repository
#  keep-history: true
#  on:
#    branch: master
branches:
  only:
    - master
notifications:
  email: false
